### ISSUE TITLE
Allow parametrization of profilers

### ISSUE THREAD

**Issue by ogxd** [ogxd/dr-dotnet#36]
# Context

Profilers will require some level of parametrization. For instance, finding the rooted path for a duplicated string will require the user to set a string name. Another example is the profiling duration for CPU profiler for instance.

# Rationale

- Each profiler must define a list of parameters it can use
- Each parameter is defined by
  - a key (PascalCase)
  - a name (human friendly)
  - a type (integer or Enum)
  - a description
  - a value (string)
- Interop will define a type to pass a blob when attaching profiler. Type will contain a session Id and a list of Parameters
- When requesting available profilers, response will include the list of defined parameters for each profiler on top of the profiler information
- UI will display parameters for a given profiler on the job page (before attaching) with an appropriate control depending on the parameter type
- There should be *no* reference to a given profiler or profiler parameter directly hardcoded in the UI. Everything should be within the profiler source code.

# Todo

- Add support for enums in FFIDJI
- Define Property, PropertyList and AttachMetadata in interop XML
- Allow definition of parameters in profilers
- Implement new interop objects serialization / deserialization in Rust
- Create UI controls for basic types (text, number, boolean)

**Comment by ogxd** [comment]
There is a limitation with FFIDJI for this use-case which is that passed objects are not built on a continuous memory segment but instead in several places. Will consider either a (big) change in FFIDJI or using protobuf instead.

**Comment by ogxd** [comment]
Protobuf does not support bust but there are some unofficial projects to do it. It seems most of them are not much maintained but it seems protobuf team plans to add official support for rust https://github.com/protocolbuffers/protobuf/commit/89d6b74

**Comment by Bluezen** [comment]
Err I juste realized we could have printed the `profiler.parameters` field of the `session.json` in the UI of the Session page.

**Comment by ogxd** [comment]
Np it's already nice for a first implementation I think.
UI could definitely be improved on many aspects
